apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
data:
  RABBITMQ_HOST: "rabbitmq"
  ASPNETCORE_URLS: "http://+:8082"
  ASPNETCORE_ENVIRONMENT: "Development"
  EMAIL_QUEUE: "email-queue"